//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PESMVC.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PES_TestEntities : DbContext
    {
        public PES_TestEntities()
            : base("name=PES_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLoginCredential> AdminLoginCredentials { get; set; }
        public virtual DbSet<CustomerLoginCredential> CustomerLoginCredentials { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Endorsement> Endorsements { get; set; }
        public virtual DbSet<InsuranceProduct> InsuranceProducts { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EndorsementStatu> EndorsementStatus { get; set; }
    }
}
