//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PESMVC.Data.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string endorsementId { get; set; }
        public string document1 { get; set; }
    
        public virtual Endorsement Endorsement { get; set; }
    }
}
