
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PESMVC.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Endorsement
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Endorsement()
    {

        this.Documents = new HashSet<Document>();

        this.EndorsementStatus = new HashSet<EndorsementStatus>();

    }


    public int Id { get; set; }

    public string endorsementId { get; set; }

    public string policyNumber { get; set; }

    public string FieldChanges { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Document> Documents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EndorsementStatus> EndorsementStatus { get; set; }

    public virtual Policy Policy { get; set; }

}

}
