
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PESMVC.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EndorsementStatus
{

    public int Id { get; set; }

    public string endorsementId { get; set; }

    public string policyNumber { get; set; }

    public string endorsementStatus { get; set; }



    public virtual Endorsement Endorsement { get; set; }

    public virtual Policy Policy { get; set; }

}

}
