//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PESMVC.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PES_TestEntities : DbContext
    {
        public PES_TestEntities()
            : base("name=PES_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Endorsement> Endorsements { get; set; }
        public virtual DbSet<InsuranceProduct> InsuranceProducts { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EndorsementStatus> EndorsementStatus1 { get; set; }
        public virtual DbSet<LoginCredential> LoginCredentials { get; set; }
    
        public virtual int createInsuranceProduct(string productName, string productLine)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var productLineParameter = productLine != null ?
                new ObjectParameter("productLine", productLine) :
                new ObjectParameter("productLine", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createInsuranceProduct", productNameParameter, productLineParameter);
        }
    
        public virtual int deleteInsuranceProduct(string insuranceId)
        {
            var insuranceIdParameter = insuranceId != null ?
                new ObjectParameter("insuranceId", insuranceId) :
                new ObjectParameter("insuranceId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteInsuranceProduct", insuranceIdParameter);
        }
    
        public virtual ObjectResult<InsuranceProduct> getAllInsuranceProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsuranceProduct>("getAllInsuranceProduct");
        }
    
        public virtual ObjectResult<InsuranceProduct> getAllInsuranceProduct(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsuranceProduct>("getAllInsuranceProduct", mergeOption);
        }
    
        public virtual ObjectResult<InsuranceProduct> getInsuranceProductById(string insuranceId)
        {
            var insuranceIdParameter = insuranceId != null ?
                new ObjectParameter("insuranceId", insuranceId) :
                new ObjectParameter("insuranceId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsuranceProduct>("getInsuranceProductById", insuranceIdParameter);
        }
    
        public virtual ObjectResult<InsuranceProduct> getInsuranceProductById(string insuranceId, MergeOption mergeOption)
        {
            var insuranceIdParameter = insuranceId != null ?
                new ObjectParameter("insuranceId", insuranceId) :
                new ObjectParameter("insuranceId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsuranceProduct>("getInsuranceProductById", mergeOption, insuranceIdParameter);
        }
    
        public virtual int updateInsuranceProduct(string productId, string productName, string productLine)
        {
            var productIdParameter = productId != null ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var productLineParameter = productLine != null ?
                new ObjectParameter("productLine", productLine) :
                new ObjectParameter("productLine", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateInsuranceProduct", productIdParameter, productNameParameter, productLineParameter);
        }
    
        public virtual ObjectResult<string> createCustomer(string custName, string custAddress, string custTelephone, string custGender, Nullable<System.DateTime> custDOB, Nullable<bool> custSmoker, string custHobbies, ObjectParameter custId)
        {
            var custNameParameter = custName != null ?
                new ObjectParameter("custName", custName) :
                new ObjectParameter("custName", typeof(string));
    
            var custAddressParameter = custAddress != null ?
                new ObjectParameter("custAddress", custAddress) :
                new ObjectParameter("custAddress", typeof(string));
    
            var custTelephoneParameter = custTelephone != null ?
                new ObjectParameter("custTelephone", custTelephone) :
                new ObjectParameter("custTelephone", typeof(string));
    
            var custGenderParameter = custGender != null ?
                new ObjectParameter("custGender", custGender) :
                new ObjectParameter("custGender", typeof(string));
    
            var custDOBParameter = custDOB.HasValue ?
                new ObjectParameter("custDOB", custDOB) :
                new ObjectParameter("custDOB", typeof(System.DateTime));
    
            var custSmokerParameter = custSmoker.HasValue ?
                new ObjectParameter("custSmoker", custSmoker) :
                new ObjectParameter("custSmoker", typeof(bool));
    
            var custHobbiesParameter = custHobbies != null ?
                new ObjectParameter("custHobbies", custHobbies) :
                new ObjectParameter("custHobbies", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("createCustomer", custNameParameter, custAddressParameter, custTelephoneParameter, custGenderParameter, custDOBParameter, custSmokerParameter, custHobbiesParameter, custId);
        }
    
        public virtual int deleteCustomer(string cId)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCustomer", cIdParameter);
        }
    
        public virtual ObjectResult<Customer> getAllCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("getAllCustomers");
        }
    
        public virtual ObjectResult<Customer> getAllCustomers(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("getAllCustomers", mergeOption);
        }
    
        public virtual ObjectResult<Customer> getCustomerById(string cId)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("getCustomerById", cIdParameter);
        }
    
        public virtual ObjectResult<Customer> getCustomerById(string cId, MergeOption mergeOption)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("getCustomerById", mergeOption, cIdParameter);
        }
    
        public virtual ObjectResult<Customer> getCustomerByNameAndDob(string cName, Nullable<System.DateTime> cDOB)
        {
            var cNameParameter = cName != null ?
                new ObjectParameter("cName", cName) :
                new ObjectParameter("cName", typeof(string));
    
            var cDOBParameter = cDOB.HasValue ?
                new ObjectParameter("cDOB", cDOB) :
                new ObjectParameter("cDOB", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("getCustomerByNameAndDob", cNameParameter, cDOBParameter);
        }
    
        public virtual ObjectResult<Customer> getCustomerByNameAndDob(string cName, Nullable<System.DateTime> cDOB, MergeOption mergeOption)
        {
            var cNameParameter = cName != null ?
                new ObjectParameter("cName", cName) :
                new ObjectParameter("cName", typeof(string));
    
            var cDOBParameter = cDOB.HasValue ?
                new ObjectParameter("cDOB", cDOB) :
                new ObjectParameter("cDOB", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("getCustomerByNameAndDob", mergeOption, cNameParameter, cDOBParameter);
        }
    
        public virtual int endorsementApproval(string eId, string pN, string flag)
        {
            var eIdParameter = eId != null ?
                new ObjectParameter("eId", eId) :
                new ObjectParameter("eId", typeof(string));
    
            var pNParameter = pN != null ?
                new ObjectParameter("pN", pN) :
                new ObjectParameter("pN", typeof(string));
    
            var flagParameter = flag != null ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("endorsementApproval", eIdParameter, pNParameter, flagParameter);
        }
    
        public virtual ObjectResult<Endorsement> getAllEndorsements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Endorsement>("getAllEndorsements");
        }
    
        public virtual ObjectResult<Endorsement> getAllEndorsements(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Endorsement>("getAllEndorsements", mergeOption);
        }
    
        public virtual ObjectResult<EndorsementStatus> getAllEndorsementsStatus(string cId)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndorsementStatus>("getAllEndorsementsStatus", cIdParameter);
        }
    
        public virtual ObjectResult<EndorsementStatus> getAllEndorsementsStatus(string cId, MergeOption mergeOption)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndorsementStatus>("getAllEndorsementsStatus", mergeOption, cIdParameter);
        }
    
        public virtual int createPolicy(string custId, string productId, string policyNom, string policyNomRelation, string policyPremiumPaymentFreqn, string filePath)
        {
            var custIdParameter = custId != null ?
                new ObjectParameter("custId", custId) :
                new ObjectParameter("custId", typeof(string));
    
            var productIdParameter = productId != null ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(string));
    
            var policyNomParameter = policyNom != null ?
                new ObjectParameter("policyNom", policyNom) :
                new ObjectParameter("policyNom", typeof(string));
    
            var policyNomRelationParameter = policyNomRelation != null ?
                new ObjectParameter("policyNomRelation", policyNomRelation) :
                new ObjectParameter("policyNomRelation", typeof(string));
    
            var policyPremiumPaymentFreqnParameter = policyPremiumPaymentFreqn != null ?
                new ObjectParameter("policyPremiumPaymentFreqn", policyPremiumPaymentFreqn) :
                new ObjectParameter("policyPremiumPaymentFreqn", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createPolicy", custIdParameter, productIdParameter, policyNomParameter, policyNomRelationParameter, policyPremiumPaymentFreqnParameter, filePathParameter);
        }
    
        public virtual ObjectResult<Policy> getAllPolicy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getAllPolicy");
        }
    
        public virtual ObjectResult<Policy> getAllPolicy(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getAllPolicy", mergeOption);
        }
    
        public virtual ObjectResult<Policy> getPolicyByCustomerId(string customerId)
        {
            var customerIdParameter = customerId != null ?
                new ObjectParameter("customerId", customerId) :
                new ObjectParameter("customerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByCustomerId", customerIdParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByCustomerId(string customerId, MergeOption mergeOption)
        {
            var customerIdParameter = customerId != null ?
                new ObjectParameter("customerId", customerId) :
                new ObjectParameter("customerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByCustomerId", mergeOption, customerIdParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByCustomerNameAndDob(string customerName, Nullable<System.DateTime> customerDOB)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("customerName", customerName) :
                new ObjectParameter("customerName", typeof(string));
    
            var customerDOBParameter = customerDOB.HasValue ?
                new ObjectParameter("customerDOB", customerDOB) :
                new ObjectParameter("customerDOB", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByCustomerNameAndDob", customerNameParameter, customerDOBParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByCustomerNameAndDob(string customerName, Nullable<System.DateTime> customerDOB, MergeOption mergeOption)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("customerName", customerName) :
                new ObjectParameter("customerName", typeof(string));
    
            var customerDOBParameter = customerDOB.HasValue ?
                new ObjectParameter("customerDOB", customerDOB) :
                new ObjectParameter("customerDOB", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByCustomerNameAndDob", mergeOption, customerNameParameter, customerDOBParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByCustomerIdAndPolicyNumber(string cId, string pN)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            var pNParameter = pN != null ?
                new ObjectParameter("pN", pN) :
                new ObjectParameter("pN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByCustomerIdAndPolicyNumber", cIdParameter, pNParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByCustomerIdAndPolicyNumber(string cId, string pN, MergeOption mergeOption)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            var pNParameter = pN != null ?
                new ObjectParameter("pN", pN) :
                new ObjectParameter("pN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByCustomerIdAndPolicyNumber", mergeOption, cIdParameter, pNParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicy(string pN)
        {
            var pNParameter = pN != null ?
                new ObjectParameter("pN", pN) :
                new ObjectParameter("pN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicy", pNParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicy(string pN, MergeOption mergeOption)
        {
            var pNParameter = pN != null ?
                new ObjectParameter("pN", pN) :
                new ObjectParameter("pN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicy", mergeOption, pNParameter);
        }
    
        public virtual int updatePolicy(string custId, string policyNum, string policyNom, string policyNomRelation, string policyPremiumPaymentFreqn, string filePath, string custAddress, string custTelephone, Nullable<bool> custSmoker)
        {
            var custIdParameter = custId != null ?
                new ObjectParameter("custId", custId) :
                new ObjectParameter("custId", typeof(string));
    
            var policyNumParameter = policyNum != null ?
                new ObjectParameter("policyNum", policyNum) :
                new ObjectParameter("policyNum", typeof(string));
    
            var policyNomParameter = policyNom != null ?
                new ObjectParameter("policyNom", policyNom) :
                new ObjectParameter("policyNom", typeof(string));
    
            var policyNomRelationParameter = policyNomRelation != null ?
                new ObjectParameter("policyNomRelation", policyNomRelation) :
                new ObjectParameter("policyNomRelation", typeof(string));
    
            var policyPremiumPaymentFreqnParameter = policyPremiumPaymentFreqn != null ?
                new ObjectParameter("policyPremiumPaymentFreqn", policyPremiumPaymentFreqn) :
                new ObjectParameter("policyPremiumPaymentFreqn", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var custAddressParameter = custAddress != null ?
                new ObjectParameter("custAddress", custAddress) :
                new ObjectParameter("custAddress", typeof(string));
    
            var custTelephoneParameter = custTelephone != null ?
                new ObjectParameter("custTelephone", custTelephone) :
                new ObjectParameter("custTelephone", typeof(string));
    
            var custSmokerParameter = custSmoker.HasValue ?
                new ObjectParameter("custSmoker", custSmoker) :
                new ObjectParameter("custSmoker", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatePolicy", custIdParameter, policyNumParameter, policyNomParameter, policyNomRelationParameter, policyPremiumPaymentFreqnParameter, filePathParameter, custAddressParameter, custTelephoneParameter, custSmokerParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByPolicyNumber(string policyNumber)
        {
            var policyNumberParameter = policyNumber != null ?
                new ObjectParameter("policyNumber", policyNumber) :
                new ObjectParameter("policyNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByPolicyNumber", policyNumberParameter);
        }
    
        public virtual ObjectResult<Policy> getPolicyByPolicyNumber(string policyNumber, MergeOption mergeOption)
        {
            var policyNumberParameter = policyNumber != null ?
                new ObjectParameter("policyNumber", policyNumber) :
                new ObjectParameter("policyNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Policy>("getPolicyByPolicyNumber", mergeOption, policyNumberParameter);
        }
    
        public virtual ObjectResult<LoginCredential> validateLoginCredentials(string userId, string password, string loginType)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var loginTypeParameter = loginType != null ?
                new ObjectParameter("loginType", loginType) :
                new ObjectParameter("loginType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginCredential>("validateLoginCredentials", userIdParameter, passwordParameter, loginTypeParameter);
        }
    
        public virtual ObjectResult<LoginCredential> validateLoginCredentials(string userId, string password, string loginType, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var loginTypeParameter = loginType != null ?
                new ObjectParameter("loginType", loginType) :
                new ObjectParameter("loginType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginCredential>("validateLoginCredentials", mergeOption, userIdParameter, passwordParameter, loginTypeParameter);
        }
    
        public virtual int signUp(string cId)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("signUp", cIdParameter);
        }
    
        public virtual int createAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createAdmin");
        }
    
        public virtual ObjectResult<Nullable<int>> getAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getAdmin");
        }
    }
}
